### ISSUE TITLE
Empty Functionalities in the Data?

### ISSUE THREAD

**Issue by boyugou** [YuxiangChai/AMEX-codebase#2]
Hi, thanks for the great work for Android data. However, it seems that most of the functionality fields in the data cloned from HF are empty? Only few of them have content? 

<img width="449" alt="image" src="https://github.com/user-attachments/assets/6784a5f2-b097-4c49-8879-3dffa4838f28">

**Comment by YuxiangChai** [comment]
We only provide around 300,000 functionalities, which are from around 20000 screenshots. Based on these, we can achieve the highest element grounding accuracy on ScreenSpot mobile subset.

**Comment by boyugou** [comment]
Thanks! @YuxiangChai 
Then may I ask if there are any plans to release the full AMEX dataset, or is the current release of 300k on 20k screenshots the final version? 
Additionally, would it be possible to provide more detailed numbers regarding the 'element grounding accuracy on the ScreenSpot mobile subset'?

**Comment by YuxiangChai** [comment]
This is the full version.
<img width="587" alt="image" src="https://github.com/user-attachments/assets/ca41127b-13d3-46ac-a075-f83e1bfcce62">

**Comment by boyugou** [comment]
Got it. 300k high quality data is still excellent. Thanks

And thanks for sharing the results on ScreenSpot.
