### ISSUE TITLE
Missing Action Matching Calculation code

### ISSUE THREAD

**Issue by neerajanand321** [YuxiangChai/AMEX-codebase#3]
Hi, Thanks for the great work. 
Can you please provide the action matching calculation code that you used for AMEX dataset as AITW use annotation positions for action matching calculation and also Is there data points used in test set  shared by 'l1' and 'l2' stage of train set?

**Comment by YuxiangChai** [comment]
Sorry, we have changed our dataset codebase release scheme. We decided not to use it as a benchmark but a pure supportive and supplementary dataset for element grounding and instructive operation. The new experiment results will be updated to README and huggingface repo.
